version: '3.8'

networks:
    tasal-housing-network:

services:
    sqlserver:
       image: "mcr.microsoft.com/mssql/server"
       container_name: sqlserver
       networks:
          - tasal-housing-network
       restart: always
       environment:
           - SA_PASSWORD=Dev@12345
           - ACCEPT_EULA=Y
       ports:
           - "1433:1433"
    tasalhousing.web:
       container_name: web
       image: web
    
       build:
           context: .
           dockerfile: ./TasalHousing.web/Dockerfile
       depends_on:
           - sqlserver
       networks:
           - tasal-housing-network
       restart: always
       environment:
           - ASPNETCORE_ENVIRONMENT=Development
       ports:
           - "80:80"
           - "443:443"